document.addEventListener('DOMContentLoaded',()=>{
 const root=document.documentElement,theme=document.getElementById('theme-toggle'),meta=document.querySelector('meta[name="theme-color"]');
 const setTheme=value=>{const dark=value==='dark';root.dataset.theme=dark?'dark':'light';theme?.setAttribute('aria-pressed',String(dark));theme?.setAttribute('aria-label',dark?'Ativar modo claro':'Ativar modo escuro');if(theme)theme.querySelector('span').textContent=dark?'☼':'☾';meta?.setAttribute('content',dark?'#211915':'#dfcca6')};
 setTheme(root.dataset.theme||'light');theme?.addEventListener('click',()=>{const next=root.dataset.theme==='dark'?'light':'dark';setTheme(next);try{localStorage.setItem('dra-phaula-modelo-theme',next)}catch(e){}});
 const menu=document.getElementById('menu-toggle'),nav=document.getElementById('main-nav');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,items=document.querySelectorAll('.reveal');if(reduced||!('IntersectionObserver'in window)){items.forEach(x=>x.classList.add('visible'))}else{const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -35px'});items.forEach(x=>obs.observe(x))}
 const sections=[...document.querySelectorAll('section[id]')],links=[...document.querySelectorAll('.main-nav a')];const active=()=>{let id='inicio',y=scrollY+170;sections.forEach(s=>{if(s.offsetTop<=y)id=s.id});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+id))};addEventListener('scroll',active,{passive:true});active();
 const phone=document.getElementById('form-phone');phone?.addEventListener('input',e=>{let v=e.target.value.replace(/\D/g,'').slice(0,11);if(v.length>6)v=`(${v.slice(0,2)}) ${v.slice(2,7)}-${v.slice(7)}`;else if(v.length>2)v=`(${v.slice(0,2)}) ${v.slice(2)}`;else if(v.length)v=`(${v}`;e.target.value=v});
 document.getElementById('contact-form')?.addEventListener('submit',e=>{e.preventDefault();const g=id=>document.getElementById(id).value.trim(),labels={consulta:'Consulta médica',retorno:'Retorno de consulta',informacoes:'Informações gerais',outro:'Outro assunto'},body=['Olá, Dra. Phaula!','',`Nome: ${g('form-name')}`,g('form-phone')?`Telefone: ${g('form-phone')}`:'',g('form-email')?`E-mail: ${g('form-email')}`:'','','Mensagem:',g('form-message')].filter((x,i,a)=>x!==''||a[i-1]!=='').join('\n');location.href=`mailto:phaulinhaw2@hotmail.com?subject=${encodeURIComponent(labels[g('form-subject')]||'Contato pelo site')}&body=${encodeURIComponent(body)}`});
 document.querySelectorAll('[data-year]').forEach(x=>x.textContent=new Date().getFullYear());
});
